### ISSUE TITLE
problem in running code

### ISSUE THREAD

**Issue by tinaboya2023** [HenryJunW/TAG#3]
Hi mr @HenryJunW  
Thank you for your great code.
I have problem in running your code could you help me please?
I install all of packages you mention and I run code with below command to pretrain 
`python -m torch.distributed.launch --nproc_per_node 1 tools/run.py --pretrain --tasks vqa --datasets m4c_stvqa --model m4c_split --seed 13 --config save/exp_yaml/stvqa_tap_pretrain_w_tag_textvqa.yaml --save_dir save/m4c_split_pretrain_test training_parameters.distributed True
`

and see this problem

`
2023-04-04T11:02:27 INFO: Loading datasets
2023-04-04T11:02:27 ERROR: [Errno 2] No such file or directory: '/home/riv/TAG/pythia/../data/original_dl/ST-VQA/m4c_stvqa/st_vqaaug_imdb_train_ocr_en_largest_ocr_bbox_0_4.npy'
Traceback (most recent call last):
  File "tools/run.py", line 94, in <module>
    run()
  File "tools/run.py", line 82, in run
    trainer.load()
  File "/home/riv/TAG/pythia/trainers/base_trainer.py", line 48, in load
    self.load_task()
  File "/home/riv/TAG/pythia/trainers/base_trainer.py", line 77, in load_task
    self.dataset_loader.load_datasets()
  File "/home/riv/TAG/pythia/common/dataset_loader.py", line 23, in load_datasets
    self.train_dataset.load(**self.config)
  File "/home/riv/TAG/pythia/datasets/multi_dataset.py", line 81, in load
    dataset_instance = builder_instance.load(self._dataset_type, attributes)
  File "/home/riv/TAG/pythia/datasets/base_dataset_builder.py", line 68, in load
    dataset = self._load(dataset_type, config, *args, **kwargs)
  File "/home/riv/TAG/pythia/datasets/vqa/vqa2/builder.py", line 32, in _load
    self.dataset = self.prepare_data_set(dataset_type, config)
  File "/home/riv/TAG/pythia/datasets/vqa/vqa2/builder.py", line 84, in prepare_data_set
    dataset = cls(dataset_type, imdb_idx, config)
  File "/home/riv/TAG/pythia/datasets/vqa/m4c_stvqa/dataset.py", line 7, in __init__
    super().__init__(
  File "/home/riv/TAG/pythia/datasets/vqa/m4c_textvqa/dataset.py", line 17, in __init__
    super().__init__(
  File "/home/riv/TAG/pythia/datasets/vqa/textvqa/dataset.py", line 8, in __init__
    super().__init__(dataset_type, imdb_file_index, config, *args, **kwargs)
  File "/home/riv/TAG/pythia/datasets/vqa/vizwiz/dataset.py", line 10, in __init__
    super().__init__(dataset_type, imdb_file_index, config, *args, **kwargs)
  File "/home/riv/TAG/pythia/datasets/vqa/vqa2/dataset.py", line 28, in __init__
    self.imdb = ImageDatabase(self.imdb_file)
  File "/home/riv/TAG/pythia/datasets/image_database.py", line 33, in __init__
    self._load_imdb(imdb_path)
  File "/home/riv/TAG/pythia/datasets/image_database.py", line 37, in _load_imdb
    self._load_npy(imdb_path)
  File "/home/riv/TAG/pythia/datasets/image_database.py", line 54, in _load_npy
    self.db = np.load(imdb_path, allow_pickle=True)
  File "/home/riv/anaconda3/envs/tag/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/riv/TAG/pythia/../data/original_dl/ST-VQA/m4c_stvqa/st_vqaaug_imdb_train_ocr_en_largest_ocr_bbox_0_4.npy'
Traceback (most recent call last):
  File "/home/riv/anaconda3/envs/tag/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/riv/anaconda3/envs/tag/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/riv/anaconda3/envs/twa/lib/python3.8/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/riv/anaconda3/envs/twa/lib/python3.8/site-packages/torch/distributed/launch.py", line 255, in main
    raise subprocess.CalledProcessError(returncode=process.returncode,
subprocess.CalledProcessError: Command '['/home/riv/anaconda3/envs/tag/bin/python', '-u', 'tools/run.py', '--local_rank=0', '--pretrain', '--tasks', 'vqa', '--datasets', 'm4c_stvqa', '--model', 'm4c_split', '--seed', '13', '--config', 'save/exp_yaml/stvqa_tap_pretrain_w_tag_textvqa.yaml', '--save_dir', 'save/m4c_split_pretrain_test', 'training_parameters.distributed', 'True']' returned non-zero exit status 1.

`

How can I solve this problem?

**Comment by tinaboya2023** [comment]
Hi again,
I could find it in this [address](https://github.com/HenryJunW/TAG/blob/main/MODEL_ZOO.md)
