### ISSUE TITLE
Error torch.distributed.elastic.multiprocessing.api, when I run pretrain

### ISSUE THREAD

**Issue by tinaboya2023** [HenryJunW/TAG#4]
Hi Mr @HenryJunW 

I'm trying to run pretrain with below code.

`python -m torch.distributed.launch --nproc_per_node 1 tools/run.py --pretrain --tasks vqa --datasets m4c_stvqa --model m4c_split --seed 13 --config save/exp_yaml/stvqa_tap_pretrain_w_tag_textvqa.yaml --save_dir save/m4c_split_pretrain_resx training_parameters.distributed True`
as you know I'm running your code with one GPU 3090 and you recommend me to run with above command but I encountered with below error.
Could you help me please?
It is noteworthy that I am running on python 3.8 and pytorch with cuda 11.7 (`conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia`) because otherwise my system can't recognises torch.

```python
/home/riv/anaconda3/envs/taag/lib/python3.8/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
usage: run.py [-h] [--config CONFIG] [--tasks TASKS] [--datasets DATASETS] --model MODEL [--run_type RUN_TYPE] [-exp EXPERIMENT_NAME] [--seed SEED]
              [--config_overwrite CONFIG_OVERWRITE] [--force_restart] [--log_interval LOG_INTERVAL] [--snapshot_interval SNAPSHOT_INTERVAL]
              [--max_iterations MAX_ITERATIONS] [--max_epochs MAX_EPOCHS] [--batch_size BATCH_SIZE] [--save_dir SAVE_DIR] [--log_dir LOG_DIR]
              [--save_aug_imdb_path SAVE_AUG_IMDB_PATH] [--vocab_file  VOCAB_FILE] [--logger_level LOGGER_LEVEL] [--should_not_log]
              [-co CONFIG_OVERRIDE] [--resume_file RESUME_FILE] [--resume RESUME] [--evalai_inference EVALAI_INFERENCE]
              [--verbose_dump VERBOSE_DUMP] [--lr_scheduler LR_SCHEDULER] [--lr_steps LR_STEPS [LR_STEPS ...]] [--clip_gradients CLIP_GRADIENTS]
              [--data_parallel DATA_PARALLEL] [--distributed DISTRIBUTED] [-dev DEVICE] [-p PATIENCE] [-fr FAST_READ] [-pt LOAD_PRETRAINED]
              [-nw NUM_WORKERS] [-lr LOCAL_RANK] [--pretrain] [--use_qag] [--generate_aug_training] [--gpu GPU] [--MASTER_PORT MASTER_PORT]
              ...
run.py: error: unrecognized arguments: --local-rank=0
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 213678) of binary: /home/riv/anaconda3/envs/taag/bin/python
Traceback (most recent call last):
  File "/home/riv/anaconda3/envs/taag/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/riv/anaconda3/envs/taag/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/riv/anaconda3/envs/taag/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/riv/anaconda3/envs/taag/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/riv/anaconda3/envs/taag/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/riv/anaconda3/envs/taag/lib/python3.8/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/riv/anaconda3/envs/taag/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/riv/anaconda3/envs/taag/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
tools/run.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-04-14_19:48:23
  host      : riv-System-Product-Name
  rank      : 0 (local_rank: 0)
  exitcode  : 2 (pid: 213678)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

**Comment by HenryJunW** [comment]
Hello, thanks for your interest in our work. From your log, it looks like that the arguments 'local_rank' and 'local-rank' are different due to the different version of PyTorch. You could try to change the 'local-rank' to 'local_rank'.
